"""
linkedin_search_tool.py
-----------------------
Agent-facing wrapper around search/job_scraper.py.

The agent decides WHAT to search for.
job_scraper.py decides HOW to search LinkedIn.

Flow:

    Agent 2
       ↓
    search_linkedin_jobs(query, location, results_count)
       ↓
    search/job_scraper.py
       ↓
    LinkedIn
       ↓
    standardized job objects
"""

import json

from langchain_core.tools import tool

from search.job_scraper import search_jobs


@tool
def search_linkedin_jobs(
    query: str,
    location: str = "",
    results_count: int = 3,
) -> str:
    """
    Search LinkedIn for real job postings matching a query.

    The query should be generated from the candidate's CV and should
    describe the type of role, technologies, or skills that are relevant
    to the candidate.

    Input:
        query:
            Search terms generated by the agent.

            Example:
                "Machine Learning Engineer Python PyTorch"

        location:
            Job location.

            Example:
                "Ireland"

        results_count:
            Maximum number of jobs to return.
            Default: 3

    Output:
        JSON string containing the job postings.

        Each job contains:
            - title
            - company
            - employment_type
            - seniority
            - description
            - categories
            - requirements
            - skills
            - url
            - salary_min
            - salary_max

    Important:
        This tool only searches and scrapes LinkedIn.
        It does NOT perform skill extraction, embedding generation,
        cosine similarity, ranking, or cover-letter generation.
    """

    query = (query or "").strip()
    location = (location or "").strip()

    if not query:
        return json.dumps(
            {
                "error": "Search query cannot be empty."
            },
            ensure_ascii=False,
        )

    if results_count <= 0:
        return json.dumps(
            {
                "error": "results_count must be greater than 0."
            },
            ensure_ascii=False,
        )

    # Keep the agent from requesting an excessive number of pages/jobs.
    results_count = min(results_count, 20)

    try:
        jobs = search_jobs(
            query=query,
            location=location,
            max_jobs=results_count,
        )

        if not jobs:
            return json.dumps(
                {
                    "message": (
                        f"No LinkedIn jobs were found for query "
                        f"'{query}'"
                        + (
                            f" in '{location}'."
                            if location
                            else "."
                        )
                    ),
                    "jobs": [],
                },
                indent=2,
                ensure_ascii=False,
            )

        return json.dumps(
            jobs,
            indent=2,
            ensure_ascii=False,
        )

    except Exception as exc:
        return json.dumps(
            {
                "error": f"LinkedIn search failed: {str(exc)}",
                "query": query,
                "location": location,
            },
            indent=2,
            ensure_ascii=False,
        )